from __future__ import annotations

from typing import Any

class PyWeightBacktest:
    @classmethod
    def from_arrow(
        cls,
        data: bytes,
        digits: int = 2,
        fee_rate: float | None = 0.0002,
        n_jobs: int | None = 4,
        weight_type: str = "ts",
        yearly_days: int = 252,
    ) -> PyWeightBacktest: ...
    @classmethod
    def from_file(
        cls,
        path: str,
        digits: int = 2,
        fee_rate: float | None = 0.0002,
        n_jobs: int | None = 4,
        weight_type: str = "ts",
        yearly_days: int = 252,
    ) -> PyWeightBacktest: ...
    def stats(self) -> dict[str, Any]: ...
    def symbol_dict(self) -> list[str]: ...
    def daily_return(self) -> bytes: ...
    def yearly_return(self, min_days: int = 120) -> bytes: ...
    def dailys(self) -> bytes: ...
    def alpha(self) -> bytes: ...
    def pairs(self) -> bytes: ...
    def aggregated_pairs(self) -> bytes: ...
    def key_trades(self, top: int = 3) -> bytes: ...
    def long_stats(self) -> dict[str, Any]: ...
    def short_stats(self) -> dict[str, Any]: ...
    def segment_stats(
        self,
        sdt: int | None = None,
        edt: int | None = None,
        kind: str = "多空",
    ) -> dict[str, Any]: ...
    def long_alpha_stats(self) -> dict[str, Any]: ...
    def is_good_strategy(
        self,
        mode: str = "history",
        target_vol: float = 0.20,
        max_dd_threshold: float = 0.20,
        min_year_days: int = 200,
        recent_days: int = 252,
        min_history_days: int = 60,
    ) -> dict[str, Any]: ...

def daily_performance(returns: Any, yearly_days: int = 252) -> dict[str, Any]: ...
def top_drawdowns(returns: bytes, top: int) -> bytes: ...
def cal_yearly_days(timestamps_ms: list[int]) -> int: ...
def rolling_daily_performance(
    data: bytes,
    ret_col: str,
    window: int = 252,
    min_periods: int = 100,
    yearly_days: int | None = None,
) -> bytes: ...
