from __future__ import annotations

from typing import Any


class PyWeightBacktest:
    @classmethod
    def from_arrow(
        cls,
        data: bytes,
        digits: int,
        fee_rate: float,
        n_jobs: int,
        weight_type: str,
        yearly_days: int,
    ) -> PyWeightBacktest: ...
    def stats(self) -> dict[str, Any]: ...
    def symbol_dict(self) -> list[str]: ...
    def daily_return(self) -> bytes: ...
    def dailys(self) -> bytes: ...
    def alpha(self) -> bytes: ...
    def pairs(self) -> bytes: ...


def daily_performance(returns: Any, yearly_days: int = 252) -> dict[str, Any]: ...
