name: Release Crate

on:
  push:
    tags: ["crate-v*"]

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test -p wbt-core
      - run: cargo publish -p wbt-core --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
